language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyourideas-api
  api_key:
    secure: HvYMQFAmTTfHC5iDYukEHtko5kipsiA8bJWKkTLpJqNEqUFYVlXd0TJ6lfbnW3+oGiOt/chHuwnU4YA6dT1MNd7uCYG3tcgfqWQS8LLcPekShwj6635TW/OHyhBpcO7etdyWIO8lRLCa1yr1t6EPRRFx2X3YrhbciTRzEghK6dIBpXNJQuhkx/T19ZLjlSA8NwtOdk2MDO0bL11on9THMiZRDZAgkW399uJYUc2ocJKaCn4pKjCDf7jp7vO20v3RD/BtInk3FIIrG12Sk9P3epsQKmgs4K10bO9iDAk3QhMLzdmsgxLpnd6jiIOpl5M5+9GWphXQDB4vqDdRvjHUYsXr+lGGub7++bV6QkoDxSts/xnty4F5TTFquH5jcZbvywKdi65q/wFkC5lPDzhowfnI36GfzIB3Fbc+kmVdklb5IL4gUl8O6JVuky6Ba7+nG/oUVwzvpxpkAEE3GStNOI3vg47O9e3lgZuZxMx+8cht7SuziNlLPD7rG4C2igJ2sQVCYbJOSEaKKZN63hWmx6o0k7alOIEj67GBbfCfNlb5z3FY2VwZ114iu+mI3/YlZLVEtihWq3ZlTB2LWaFG8cocIwaswdvolTfKg2fSCy+enaujSP7GfSI/sOWvsMoyMk6PVJXkzgUcaiJTvohZTfbT6u0RvJ+MGD+UGrS0iN8=