version: "3"

services:
  api:
    build: .
    depends_on:
      - mongo 
    environment: 
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/dbPracticeArqApi
      - APPLICATION_NAME=Share Your Idea
      - JWT_SECRET=wejhriscnkv3485860o457uyuihrtm
      - CACHE_KEY=343456UHFJGQIOWEI7U536OERFNV
      - SWAGGER_DOC=swaggerPROD
    ports: 
      - "5000:5000"
    
  mongo:
    image: mongo